# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Set values specific to:
#   salt['config.get']('osarch') == aarch64.
#
# You just need to add the key:values for this `osarch` that differ
# from `defaults.yaml`.
#
# If you do not need to provide defaults via the `osarch` config,
# you can remove this file or provide at least an empty dict, e.g.
# values: {}
---
values:
  arch: aarch64
  pkg:
    docker:
      use_upstream: archive
      archive:
        source_hash: '5d6ede3368eac8e74ead70489aa7e4e663fe1ccfbb9763a6ac55991d55b70354'
      suffix: tgz
...
